language: android

jdk: oraclejdk8

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-24.0.2

    # The SDK Version
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch

script: ./gradlew connectedAndroidTest