language: android

jdk: oraclejdk8

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-24

    # The SDK Version
    - android-22
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

 licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'